# Site settings
title: "Alexander Machon"
bye_message: "Thx!"
baseurl: "/machonalex/"
url: "https://machonaleks2.github.io"
disqus: gjuniioor

# Header settings
nick: "Alexander Machon"
mail:
    domain: "machon.aleks@gmail.com"
source_code:
    server: "github.com"
    nick: "machonaleks2"
blog:
    server: "wordpress.com"
    nick: "gjuniioor"
linkedin:
    server: "linkedin"
# Build settings
markdown: kramdown
permalink: /:categories/:title/
