# Site settings
title: "Alexander Machon"
bye_message: "Thx!"
baseurl: ""
url: "https://www.machonalex.com/"

# Header settings
nick: "Alexander Machon"
mail:
    domain: "machon.aleks@gmail.com"
source_code:
    server: "github.com"
    nick: "machonaleks2"
linkedin:
    server: "linkedin"
# Build settings
markdown: kramdown
permalink: /:categories/:title/
